name: CMake Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - {
          name: "Windows 32Bit", artifact: "gmcl_pndiscord_win32.dll",
          cmakeargs: "-A Win32"
        }
        - {
          name: "Windows 64Bit", artifact: "gmcl_pndiscord_win64.dll",
          cmakeargs: "-A x64"
        }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      env:
        cmakeargs: ${{matrix.config.cmakeargs}}
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/cpp $cmakeargs

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target pndiscord --config MinSizeRel

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.config.artifact}}
        path: ${{runner.workspace}}\build\MinSizeRel\${{matrix.config.artifact}}

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install package
      run: |
        sudo apt-get update && sudo apt-get -y install gcc-multilib g++-multilib

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/cpp

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target pndiscord

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "gmcl_gdiscord_linux.dll"
        path: ${{runner.workspace}}/build/gmcl_pndiscord_linux.dll

  linux64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/cpp -D64BIT=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target pndiscord

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "gmcl_gdiscord_linux64.dll"
        path: ${{runner.workspace}}/build/gmcl_pndiscord_linux64.dll
